version: '3.8'
services:
  contactapp:
    build: ./.
    env_file:
      - ./docker.env
    ports:
      - 4000:4000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
    - ./app:/home/app/app